import Head from 'next/head';

export default function Home() {
  return (
    <div className='px-8'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex flex-1 flex-col items-center justify-center min-h-screen py-16'>Hello, Next.js</div>
    </div>
  );
}
